### PR TITLE
Paging and sorting

### PR DESCRIPTION
**Pull request by groldan**
Fix paging and add sorting

Limit/offset wasn't being applied correctly.

Added sorting through the sortby paramter.

Add `filter-lang`, `filter-crs`, and `sortby` parameteres to the API definition

### CODE REVIEW

**Comment by jeanpommier** [comment]
> Add `filter-lang`

What's `filter-lang` about ?

**Comment by groldan** [comment]
`filter-lang` is an enum allowing to specify which predicate language the `filter` parameter value is expressed in.

**Comment by jeanpommier** [comment]
ah, nice. Thanks. It might be worth documenting

**Comment by groldan** [comment]
It's documented in the api (swagger ui) and it's part of the spec

**Comment by jeanpommier** [comment]
Oh, right, sorry. Thank you Gabriel

**Pull request merged**
